sudo: required

services:
  - docker

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - composer install --no-dev --prefer-dist
  - docker build . -t freeelphants/thruway:0.1.0

after_success:
#   Coverage reporting
  - bash <(curl -s https://codecov.io/bash)
  - if [ -z "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi


cache:
  directories:
    - $HOME/.composer/cache