services:
  app:
    image: ${DOCKER_DEV_IMAGE}:${REVISION}
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - ./cli/:/srv/thruway/cli/
      - ./src/:/srv/thruway/src/
      - ./config/:/srv/thruway/config/
      - ./vendor/:/srv/thruway/vendor/
    command: php cli/router.php
